---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------
### Scatter plot
```{r}
library(rnoaa)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())



```

```{r}
weather %>% 
  mutate(hover_text = str_c("Date: ", date,'\nName: ', name)) %>% 
  plot_ly(x = ~tmin, y = ~tmax, color = ~prcp,
          text = ~hover_text,
          type = "scatter", mode = "marker", alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------
### Bar chart

```{r}
weather%>%
  separate(date, into = c("year","month","day"), sep = "-")%>%
  group_by(month,name)%>%
  summarize(t = mean(tmax))%>%
  plot_ly(x= ~month, y= ~t, color = ~name, type = "bar")
```


### Box plot

```{r}
weather %>%
  mutate(month = fct_reorder(name, prcp),diff_in_t = tmax-tmin) %>%
  plot_ly(x = ~name, y = ~diff_in_t, color = ~name,
          colors = "Set2",
          type = "box") 
```



